#!/bin/bash

#title : apt-cleanup
#description : Cleans up install packages
#author :Kris Occhipinti
#site :http://filmsbykris.com
#date :Tue Jun 3 12:32:23 EDT 2014
#version :1
#usage :sudo ./apt-cleanup
#notes :run as sudo or root
#License :GPLv3 http://www.gnu.org/licenses/gpl-3.0.html

apt-get autoclean -y
apt-get clean -y
apt-get autoremove -y
apt-get install gtkorphan -y
